url: "https://docs.reconmap.com"
baseurl: ""
title: "Reconmap Docs"
description: "Open-source pentesting collaboration tool for teams with automation and reporting features"
logo: "/images/logo.png"
color_scheme: wider

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
ga_tracking: UA-175514417-1
twitter:
  username: Reconmap
  card: summary

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/reconmap/documentation"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - CREDITS
  - CNAME
  - README.md
