title: "Reconmap"
color_scheme: "dark"
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
ga_tracking: UA-175514417-1

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
